# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 050c6b39ac13883bef1b326f70027b820b4598545242650658c599bc4f67b538fbee4e3ac7fe0eec0a0efc57b34200835317a199c8f751aaa129e1bf491a5031

test:
  secret_key_base: 1bf9418b2051b0055ed9f99111299c0ae511acd3b30d5cd57794243b00c0c7e8612b1214c9c98c1981fdfdbc6a884a03e3cb282b4ac042edb9d3b07ae0b7a42d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
